# Generated by Django 5.1.2 on 2025-03-02 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_codesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('input_data', models.TextField(blank=True, null=True)),
                ('output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.ktp')),
                ('tasktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.tasktype')),
            ],
        ),
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
